#!/bin/bash

touch ~/.emufun
source ~/.emufun

[[ $GAMEDIR ]] || GAMEDIR="$HOME/Games"

while true; do
    (cd "$GAMEDIR" && find -type f) | love . | {
        read CFG
        read ROM
        env ROM="$GAMEDIR/$ROM" CFG="$GAMEDIR/$CFG" sh "$GAMEDIR/$CFG"
    }
    [[ $1 ]] || exit
done
